name: AI Changelog

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  models: read

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate chagelog
        uses: decoded-cipher/auto-changelog@v1.0.0
        with:
          output_path: CHANGELOG.md